version: '3.8'
services:
  sql_db:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'sql_db'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: '*strong123'
    ports:
      - '1433:1433'
  net_api:
    build: './school-control-api/'
    container_name: 'school-control-net-api'
    ports:
      - '8080:80'
    depends_on:
      - sql_db
  angular_front:
    build: './school-control-front/'
    container_name: 'school-control-angular'
    ports:
      - '4200:80'
    depends_on:
      - net_api